# Generated by Django 2.1.12 on 2020-03-30 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Apellido_Materno',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
